### ISSUE TITLE
Should we consider using properties?

### ISSUE THREAD

**Issue by CXCubeHD** [LunityClient/Lunity#13]
In C# we have so called Properties
```cs
class C
{
	int Count { get { return 10; } set { ... } }
}
```

C++ on its own doesn't really have it (unless you mess with it around) but most **major compilers** like **Clang**, **MsBuild** support this: ``__declspec(property(get=GetFunction, put=Setfunction)) int Count;``
with macros you can even improve the syntax:
```cpp
struct S
{
	int GetFunc() { return 10; }
	void SetFunc(int value) { ... }
	Property(get = GetFunc, set = SetFunc) int Count;
};
```

Then u can use it like this: ```auto a = s.Count;```
instead of this: ```auto a = s.Count();``` or ```auto a = s.GetCount();```

I think this would improve syntax a lot and I really hope that we can use it.

**Comment by DisabledMallis** [comment]
May be helpful for dynamic structs and other SDK/Bridge related stuff, but I think we should generally avoid it.
