### ISSUE TITLE
WHAT THE FUCK

### ISSUE THREAD

**Issue by okureta** [LunityClient/Lunity#2]
WHAT THE ASBOLUTE FUCK IS THIS **BULLSHITTERY** WHY IS THE FUCKING LIB FOLDER LABELED AS PACKAGES?

**Comment by DisabledMallis** [comment]
Cuz nuget

**Comment by okureta** [comment]
> Cuz nuget

holy cringe rename it lib rn or die

**Comment by 12brendon34** [comment]
chill
