### ISSUE TITLE
How do i run Lunity?

### ISSUE THREAD

**Issue by c0ntr0x2334** [LunityClient/Lunity#3]
and this might not be a problem but why does it say no dll found, does it make the dll when not in debug?

**Comment by c0ntr0x2334** [comment]
Youre using a debug build!

Lunity injector by ASM
Verifying Lunity...

Missing Lunity.dll!
An error occoured during Lunity verification...
For help, join this server: https://discord.gg/gNdBNTT
When asking for help, please supply the ENTIRE error above.

**Comment by c0ntr0x2334** [comment]
link expired for discord

**Comment by DisabledMallis** [comment]
thanks for letting me know ill update the link rn
